### PR TITLE
feat: switch-to-sdk-style-project

### LINKED ISSUE #8: Feature: Switch to SDK-Style Project
**Is your feature request related to a problem? Please describe.**
It is not really a problem, the current project format is simply outdated.

**Describe the solution you'd like**
- Migrate the `ResourceFileEditor.csproj` file to the new SDK-Style
- Add the `Directory.Build.props` file to add the basic metadata information for the project(s)
- Add the `Directory.Build.targets` file to add specific target build instructions for the project(s)
- Migrate from `packages.config` to `PackageReference`

**Describe alternatives you've considered**
None. ;)

**Additional context**
After the changes , the `AssemblyInfo.cs` should be get auto generated, this behavior can be set to `true` or `false`.
If it gets auto generated, the `AssemblyInfo.cs` should be added to the `.gitignore` file.

```csharp
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("https://github.com/MadDeCoDeR")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © 2024 MadDeCoDeR")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("This is a file manager for DOOM 3 BFG Edition/DOOM 3 (2019) .resources files. It " +
    "allows you to see, extract, delete, preview and edit the files inside .resources" +
    " files. Also it allows you to create and edit .resource files.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.225.624")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.225.624-Development+e77fa2c346f376b021c1a8364a1baae211165a96")]
[assembly: System.Reflection.AssemblyProductAttribute("BFG Resource File Manager")]
[assembly: System.Reflection.AssemblyTitleAttribute("ResourceFileEditor")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.225.624")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/MadDeCoDeR/BFG-Resource-File-Manager")]
[assembly: System.Resources.NeutralResourcesLanguageAttribute("en-US")]

// Generated by the MSBuild WriteCodeFragment class.
```

What gets generated and how, can be controlled within the `Directory.Build.props` file.

```xml
<Project>

	<PropertyGroup Label="DateData">
		<CurrentYear>$([System.DateTime]::UtcNow.Year)</CurrentYear>
		<CurrentMonth>$([System.DateTime]::UtcNow.Month)</CurrentMonth>
		<CurrentDay>$([System.DateTime]::UtcNow.Day)</CurrentDay>
	</PropertyGroup>

	<!-- Currently only major and minor are indented to be set able.  -->
	<PropertyGroup Label="VersionData">
		<VersionMajor>1</VersionMajor>
		<VersionMinor>0</VersionMinor>
		<VersionPatch>$(CurrentMonth)$(CurrentDay)</VersionPatch>
		<VersionRevision>$([System.DateTime]::UtcNow.TimeOfDay.TotalMinutes.ToString("0"))</VersionRevision>
		<VersionPrefix>$(VersionMajor).$(VersionMinor).$(VersionPatch).$(VersionRevision)</VersionPrefix>
		<VersionSuffix Condition="$(Configuration.Equals('Debug'))">Development</VersionSuffix>
	</PropertyGroup>

	<PropertyGroup Label="TechnicalData">
		<AllowUnsafeBlocks>false</AllowUnsafeBlocks>
		<AnalysisLevel>latest</AnalysisLevel>
		<AnalysisMode>recommended</AnalysisMode>
		<AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
		<CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
		<DebugType>full</DebugType>
		<Deterministic>true</Deterministic>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<EnablePackageValidation>true</EnablePackageValidation>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<GeneratedAssemblyInfoFile>Properties\AssemblyInfo.cs</GeneratedAssemblyInfoFile>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<TargetFrameworks>net48</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<DebugType>none</DebugType>
	</PropertyGroup>

	<PropertyGroup Label="MetaData"	Condition="!$(MSBuildProjectName.EndsWith('Tests'))">
		<Author>MadDeCoDeR</Author>
		<Authors>$(Author)</Authors>
		<Company>https://github.com/$(Author)</Company>
		<Copyright>Copyright © $(CurrentYear) $(Author)</Copyright>
		<Description>This is a file manager for DOOM 3 BFG Edition/DOOM 3 (2019) .resources files. It allows you to see, extract, delete, preview and edit the files inside .resources files. Also it allows you to create and edit .resource files.</Description>
		<Product>BFG Resource File Manager</Product>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/MadDeCoDeR/BFG-Resource-File-Manager</RepositoryUrl>
		<NeutralLanguage>en-US</NeutralLanguage>
		<Title>$(AssemblyName)</Title>
	</PropertyGroup>

	<PropertyGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
		<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
		<Using Include="System.Diagnostics" />
		<Using Include="System.Diagnostics.CodeAnalysis" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Properties\" />
	</ItemGroup>

</Project>
```

### PR DESCRIPTION
**Pull request by BoBoBaSs84**
changes:
- modified the `ResourceFileEditor.csproj` file
- added the `Directory.Build.props` file
- added the `Directory.Build.targets` file
- removed the `packages.config` file
- removed other unnecessary or nut used files
- removed unused packages
- removed reference to `Visual.Basic` -> this lead into a new dialog
- modiefied `ManagerUi.cs` due to remove of `Visual.Basic`

closes #8

### CODE REVIEW

**Comment by BoBoBaSs84** [comment]
I'm changing this to `draft`. I need to test the new `add entry dialog` first.
Or later, I'm going for lunch now. 😄

**Comment by BoBoBaSs84** [comment]
Okay, the new Dialog is a bit huge but it should do the trick.
AddEntryDialog
ShouldDoTheTrick

**Comment by MadDeCoDeR** [comment]
Hi there just a quick question how did you did the switch? I want to replicate the pr in order to review it

**Comment by BoBoBaSs84** [comment]
I did the switch in this [branch ](https://github.com/BoBoBaSs84/BFG-Resource-File-Manager/tree/feature/switch-to-sdk-style-project)

**Comment by BoBoBaSs84** [comment]
If there is a better way to collaborate, please let me know.

**Comment by MadDeCoDeR** [comment]
> If there is a better way to collaborate, please let me know.

Nah that way is fine

**Comment by MadDeCoDeR** [comment]
The ui seems ok. I will merge it and see what damage the other stuff will do

**Comment by MadDeCoDeR** [comment]
I also fix the styling of the pop up and made it smaller

**Pull request merged**
